version: '3.8'
services:
        rabbitmq:
                image: rabbitmq:3-management
                container_name: rabbitmq
                ports:
                        - "5672:5672"
                        - "15672:15672"
                environment:
                        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
                        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
                volumes:
                        - rabbitmq-data:/var/lib/rabbitmq
                networks:
                        - rabbitmq-net
volumes:
        rabbitmq-data:
networks:
        rabbitmq-net:
                driver: bridge
                external: true
